#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook "build-essential"
cookbook "bluepill"
cookbook "runit"
cookbook "nginx"
cookbook "unicorn"
cookbook "imagemagick"
cookbook "openssl"
cookbook "database"
cookbook "mysql"

cookbook "nodejs",
  :git => 'https://github.com/mdxp/nodejs-cookbook'
cookbook "redis",
  :git => 'https://github.com/ctrabold/chef-redis'


# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
